//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Comparison.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCErrorLogger
    {
        public int ErrorID { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorSource { get; set; }
    }
}
