// <auto-generated />
namespace ProductComparison.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MigProd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigProd));
        
        string IMigrationMetadata.Id
        {
            get { return "201404111835132_MigProd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
