// <auto-generated />
namespace ProductComparison.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MigRep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigRep));
        
        string IMigrationMetadata.Id
        {
            get { return "201404111837509_MigRep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
